### ISSUE TITLE
Fix custom stacktrace indent

### ISSUE THREAD

**Issue by Bartvds** [Bartvds/mocha-unfunk-reporter#14]
Do not left-trim the stack-trace:

For example: when using for Q.longStackSupport promises the `From previous event:`-line should be on different indent level then the `at`'s:

```
         at Function.assert.jsonOf (index.js:105:40)
         From previous event:
         at Context.<anonymous> (API.ts:101:7)
```

**Comment by Bartvds** [comment]
Fixed in 0.3.6
